### ISSUE TITLE
csdn文章里面有的图片保存PDF后里面展示的宽度不够

### ISSUE THREAD

**Issue by RXlung** [doublesweet01/BS_script#1]
当csdn保存的时候 
在pdf中有的图片保存下来宽度可能显示不够

--感谢插件！！超级好用！！

**Comment by dossweet** [comment]
方便给下显示不全的网址并说下什么浏览器吗

**Comment by RXlung** [comment]
https://blog.csdn.net/qq_27489007/article/details/118052394?spm=1001.2014.3001.5501
比如第一张图 虽然是gif 保存的时候跳出来的pdf页  图片右侧少一部分
谷歌浏览器和Edge浏览器都试过了
