### ISSUE TITLE
不能在知乎使用

### ISSUE THREAD

**Issue by aqlkzf** [doublesweet01/BS_script#3]
之前在知乎是正常的，
现在问题如下
+ 对于网页已经正常显示（渲染后）的latex 公式，打印的pdf空白
+ 对于网页还未渲染的latex源码，打印出来是源码

csdn使用是正常的，已经重装过插件，重装过chrome，依旧不能正常使用。
附上打印错误的pdf  网址 https://zhuanlan.zhihu.com/p/337575425

![image](https://user-images.githubusercontent.com/67051837/184848921-909e16c4-ebfd-4109-96ea-a70fee082b95.png)

**Comment by dossweet** [comment]
您好，该问题已在V10.11版本中修复，请更新脚本~
