### ISSUE TITLE
在知乎打印时公式会重复一遍

### ISSUE THREAD

**Issue by haoxinlv** [doublesweet01/BS_script#4]
测试中已经关闭了其它脚本，仍然有这个现象，浏览器是Edge 107.0.1418.26，Tampermonkey v4.16.1，脚本是最新的10.11
<img width="565" alt="image" src="https://user-images.githubusercontent.com/20655049/198874797-00e51e18-b4c7-400c-bc18-3e82035514e6.png">

**Comment by dossweet** [comment]
能否再详细描述一下问题？最好附一下网页地址。

**Comment by haoxinlv** [comment]
经过更多测试，当打印问题的回答时，会出现公式重复的情况，新发现打印文章时文章中公式有的显示两遍，有的是一遍
出问题的回答地址： https://www.zhihu.com/question/342590576/answer/852699974
专栏文章地址： https://zhuanlan.zhihu.com/p/293404382
另外：换了Chrome，问题仍然存在
<img width="998" alt="image" src="https://user-images.githubusercontent.com/20655049/198878671-7534b1db-5d2b-4289-b359-2dfa339758f7.png">
（问答中所有公式都显示了两遍）
<img width="997" alt="image" src="https://user-images.githubusercontent.com/20655049/198878747-fc824c5f-ec3c-40c7-870e-7e6c6685a788.png">
<img width="997" alt="image" src="https://user-images.githubusercontent.com/20655049/198878772-14c40d36-12f8-4226-862a-0374dc8dbe18.png">
（文章中公式有的显示两遍，有的是一遍）
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/20655049/198878834-95a93c67-c71c-482e-8e24-371e2831212b.png">
（Chrome中问题依然存在）

**Comment by dossweet** [comment]
好的，我看看能否修复。如果您愿意的话，也可以自己研究下如何解决。如果您优化了脚本，我会将您添加为本项目的核心开发者。

**Comment by dossweet** [comment]
问题已修复，请更新最新版本体验~
